name       : python-zipp
version    : 1.2.0
release    : 7
source     :
    - https://pypi.io/packages/source/z/zipp/zipp-1.2.0.tar.gz : c70410551488251b0fee67b460fb9a536af8d6f9f008ad10ac51f615b6a521b1
homepage   : https://github.com/jaraco/zipp
license    : MIT
component  : programming.python
summary    : Backport of pathlib-compatible object wrapper for zip files
description: |
    Backport of pathlib-compatible object wrapper for zip files
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-more-itertools
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
