name       : python-zipp
version    : 0.6.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/57/dd/585d728479d97d25aeeb9aa470d36a4ad8d0ba5610f84e14770128ce6ff7/zipp-0.6.0.tar.gz : 3718b1cbcd963c7d4c5511a8240812904164b7f381b647143a89d3b98f9bcd8e
license    : MIT
component  : programming.python
summary    : Backport of pathlib-compatible object wrapper for zip files
description: |
    Backport of pathlib-compatible object wrapper for zip files
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-more-itertools
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
